name: Nightly Build Test Output Job Status

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:
    
permissions:
  contents: read
  packages: write

jobs:
  scala-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Create Job Badge
      uses: ./.github/actions/create-job-status-badge
      if: ${{ always() }}
      with:
        secret: ${{ secrets.GIST_SECRET }}
        gist-id: 7495dccc42118020c12de5a095cfa2a6
        file-name: nb-scala-build.json
        type: job
        job-name: scala-build

  docker-build-bigdl:
    needs: scala-build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: docker login
      run: |
        docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}'
      
    - name: Create Job Badge
      if: ${{ always() }}
      uses: ./.github/actions/create-job-status-badge
      with:
        secret: ${{ secrets.GIST_SECRET }}
        gist-id: aaee1abb17ed9aad37e19256787c52b2
        file-name: nb-docker-build-bigdl.json
        type: job
        job-name: docker-build-bigdl


  
  docker-build-ppml:
    needs: scala-build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Job Badge
      if: ${{ always() }}
      uses: ./.github/actions/create-job-status-badge
      with:
        secret: ${{ secrets.GIST_SECRET }}
        gist-id: bc8a699b455bced4a1aef138ad5df07e
        file-name: nb-docker-build-ppml.json
        type: job
        job-name: docker-build-ppml

  
  docker-build-kms:
    needs: scala-build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Create Job Badge
      if: ${{ always() }}
      uses: ./.github/actions/create-job-status-badge
      with:
        secret: ${{ secrets.GIST_SECRET }}
        gist-id: 966d4c0bf23c67662120d1bf4b1c88dc
        file-name: nb-docker-build-kms.json
        type: job
        job-name: docker-build-kms



  python-build-sourceforge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Create Job Badge
      if: ${{ always() }}
      uses: ./.github/actions/create-job-status-badge
      with:
        secret: ${{ secrets.GIST_SECRET }}
        gist-id: 6d878630c0c8f50c388bb7e196354ca8
        file-name: nb-python-sourceforge-build.json
        type: job
        job-name: python-build-sourceforge
        
        
  create-workflow-badge:
    runs-on: ubuntu-latest
    steps:
    - name: create workflow badge
      if: ${{ always() }}
      uses: ./.github/actions/create-job-status-badge
      with:
        secret: ${{ secrets.GIST_SECRET }}
        gist-id: 48dbd87983219d4fe264adfea701815a
        file-name: nightly-build-test-job-status.json
        type: workflow
        

      
